<?php
	
	$carbon_general_options= array( array(
		"name" => "Newsletter",
		"type" => "title",
		"img" => CARBON_IMAGES_URL."icon_general.png"
	),
	
	array(
		"type" => "open",
		"subtitles"=>array(array("id"=>"newsletter", "name"=>"Newsletter Code"))
	),
	
	
	
	/* ------------------------------------------------------------------------*
	 * Top Panel
	 * ------------------------------------------------------------------------*/
	
	array(
		"type" => "subtitle",
		"id"=>'newsletter'
	),
	
	array(
		"type" => "documentation",
		"text" => "<h3>Mail Chimp Newsletter</h3>"
	),
	
	array(
		"name" => "Newsletter <b>First Text</b>",
		"id" => "carbon_newsletter_text",
		"type" => "text",
		"desc" => "Set the <b>Subscribe Now</b> text.<br/> NOTE: If you add links, span or class <b>do not use quotes or double quotes</b>.<br/> ex: < span class=text_color > "
	),
	
	array(
		"name" => "Newsletter <b>Second Text</b>",
		"id" => "carbon_newsletter_stext",
		"type" => "text",
		"desc" => "Set the Newsletter Second text"
	),

	array(
		"name" => "Newsletter <i>Input</i> text",
		"id" => "carbon_newsletter_input_text",
		"type" => "text",
		"desc" => "Set the <i>Enter your e-mail</i> text"
	),

		
	array(
		"name" => "Mail Chimp Code",
		"id" => "carbon_mailchimp_code",
		"type" => "textarea",
		"desc" => "Use this textbox to paste the code generated by MailChimp.<br/>Create Form > Share It > Click - Create HTML code for a small subscribe form"
	),
	
	array(
		"type" => "documentation",
		"text" => '<h3>Newsletter</h3>'
	),
	
	array(
		"name" => "Display Newsletter on Footer ?",
		"id" => "carbon_newsletter_enabled",
		"type" => "checkbox",
		"std" => 'off',
		"desc" => "Enables the use and display of the Mail Chimp Subscription Form on Pages."
	),

	array(
		"type" => "close"
	),
	
	/*close array*/
	
	array(
		"type" => "close"
	));
	
	carbon_add_options($carbon_general_options);
	
?>